### ISSUE TITLE
Add branch filter in cloudformation

### ISSUE THREAD

**Issue by lentusignavus** [awsdocs/aws-codebuild-user-guide#13]
Echoing this comment: https://github.com/awsdocs/aws-codebuild-user-guide/issues/1#issuecomment-454738371

The cloudformation template docs for codebuild doesn't include a way to add a branch filter for the codebuild project (if there is a way)

**Comment by sluipmoord** [comment]
@lentusignavus 
I could not find a way to do this via cloud formation

You can use the CLI to add the filter 
`aws codebuild update-webhook --project-name your-project-name --branch-filter ^develop$ `

But I ended up writing a python script to create the code build stack and update it after words

```
import boto3

codebuild = boto3.client("codebuild")

......

response = update_or_create_stack(stack_name, params)
for stack in response["Stacks"]:
            for output in stack["Outputs"]:
                if output["OutputKey"] == "CodeBuildProjectName":
                    codebuild.update_webhook(
                        projectName=output["OutputValue"], branchFilter=branch
                    )
```
and made sure to output the project name in the cloud formation stack
```
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project

....

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
```
