### ISSUE TITLE
Using Ubuntu with Sample Docker Custom Image will fail

### ISSUE THREAD

**Issue by TimPietrusky** [awsdocs/aws-codebuild-user-guide#2]
## Issue description
The documentation [sample-docker-custom-image.md](https://github.com/awsdocs/aws-codebuild-user-guide/blob/master/doc_source/sample-docker-custom-image.md) is describing what needs to be done in CodeBuild when using a custom image to start Docker in the `buildspec.yml`:

```
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
```

This is only working if you are using alpine, but not for example for Ubuntu. 

As my custom image for CodeBuild is based on Ubuntu, I can't use this snippet without a modification like this (remove the `-t` from `timeout`):

```
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
```

I would like to update documentation to also add an example for Ubuntu. Are you fine with this? Or how should this be addressed? 

## Steps to reproduce
* Open the documentation
* Create a custom Docker Image for CodeBuild using Ubuntu
* Use the provided command to start Docker
