### ISSUE TITLE
env variable composition is not supported

### ISSUE THREAD

**Issue by brainstorm** [awsdocs/aws-codebuild-user-guide#55]
Given:

```yaml
version: 0.2
run-as: root
env:
    variables:
        "CONTAINER_NAME": "umccrise"
        "CONTAINER_REPO_NAME": "$CONTAINER_NAME"
        "CONTAINER_REPO_URL": "SOMEID.dkr.ecr.ap-southeast-2.amazonaws.com/$CONTAINER_REPO_NAME"
```

The expansion for `$CONTAINER_REPO_URL` on runtime is wrong (by bash/reasonable standards):

```
[Container] 2020/03/05 01:27:54 Running command echo $CONTAINER_REPO_URL/$CONTAINER_NAME
SOMEID.dkr.ecr.ap-southeast-2.amazonaws.com/$CONTAINER_REPO_NAME/umccrise
```

IMHO, it should really expand the imbricated en vars recursively:

```
[Container] 2020/03/05 01:27:54 Running command echo $CONTAINER_REPO_URL/$CONTAINER_NAME
SOMEID.dkr.ecr.ap-southeast-2.amazonaws.com/umccrise/umccrise
```

Shall I do a pull request to clarify this bit? I lost a bit of time figuring this non-intuitive CodeBuild behaviour.

/cc @reisingerf @victorskl @vladsaveliev
